### ISSUE TITLE
Reverse shaped characters in RTL mode

### ISSUE THREAD

**Issue by michal-h21** [deepakjois/luaharfbuzz#17]
In LuaTeX, if we use `\textdir TRT` command, which we should use for RTL texts, it reverses the shaped text. In SILE, it is solved in this way:

    hb_buffer_guess_segment_properties(buf);
    hb_buffer_get_segment_properties(buf, &segment_props);
    shape_plan = hb_shape_plan_create_cached(hbFace, &segment_props, features, nFeatures, NULL);
    int res = hb_shape_plan_execute(shape_plan, hbFont, buf, features, nFeatures);

    if (direction == HB_DIRECTION_RTL) {
      hb_buffer_reverse(buf); /* URGH */
    }
    glyph_info   = hb_buffer_get_glyph_infos(buf, &glyph_count);
    glyph_pos    = hb_buffer_get_glyph_positions(buf, &glyph_count);

**Comment by deepakjois** [comment]
This issue has made me rethink how the `harfbuzz.shape(…)` function should work. It currently returns a table with shaped glyphs because I copied the initial logic from SILE. However, the actual `hb_shape` (which I am wrapping) does not return any values at all.

I could implement the logic above that SILE implements, but I would like to stick as far as possible to the original API semantics. This will require that instead of calling `hb_buffer_reverse(…)` in `harfbuzz.shape(…)`, the client instead performs a check on the direction and calls `hb_buffer_reverse` (or a wrapped method `buffer:reverse(…)` in our case) if required. It will also mean a breaking API change to `harfbuzz.shape(…)`, but that is okay. We don’t really have many (any?) people using luaharfbuzz at this point, and it is worth preserving the original API semantics in the long run.

So my proposal is:

1. Make `buffer:shape(…)` not return any values, to preserve Harfbuzz API semantics
2. Add a helper method `buffer:get_glyphs_and_positions(…)` to return the shaped glyphs.
3. Wrap the `hb_buffer_reverse(…)` as `buffer:reverse(…)`

After this, the client code would look like this:
```lua
buffer:shape(font,text,options)
if options.direction == "rtl" then buffer:reverse() end
glyphs = buffer:get_glyps_and_positions()
```

What do you think?

**Comment by michal-h21** [comment]
Yeah, it sounds like a good plan, it is much more transparent than doing some magic in the shaping function.

**Comment by deepakjois** [comment]
Ok, did parts 1 and 2 above. Will do 3 soon.

**Comment by deepakjois** [comment]
This is done now.
