### ISSUE TITLE
Buffer.add_utf8 should expose the item offset and length arguments

### ISSUE THREAD

**Issue by khaledhosny** [deepakjois/luaharfbuzz#20]
The last two arguments of `hb_buffer_add_utf8()` are the offset of the part of the text to be shaped and its length, respectively. This should be exposed to clients in case only a part of the text is being shape (e.g. a text with mixed direction and/or scripts after being itemized, or after font fallback).

Giving the whole text and specifying an offset an length of the part to be shaped is preferred to just passing the substring to HarfBuzz, as it uses the extra context to e.g. do proper Arabic shaping across items or to  determine if the shaped part is the start of the text (affects how accents at the start of the text are handled).

**Comment by deepakjois** [comment]
This is an oversight on my part, probably because I was blindly copying what SILE was doing. I did not realise `hb_buffer_add_utf8` took more than 3 arguments. It definitely needs to be fixed.

It would also nice if the Lua part of the API exposed to the client makes the `item_offset` and `item_length` arguments optional, and have it such that:

* If `item_offset` is nil and `item_length` is nil  the default values (`0` and `-1` respectively) are used
* If only `item_length` is nil, the default value (`-1`) is used

This means all the following calls will be valid:
```lua
buf:add_utf8('some string') -- hb_buffer_add_utf8(buf, strlen(buf), 0, -1)
buf:add_utf8('some string',2) -- hb_buffer_add_utf8(buf, strlen(buf), 2, -1)
buf:add_utf8('some string',2,3) -- hb_buffer_add_utf8(buf, strlen(buf), 2, 3)
```

This would have the side-effect of preserving the existing semantics as well (although that is not strictly necessary at this point).

WDYT?

**Comment by khaledhosny** [comment]
Sounds good.
