### ISSUE TITLE
[luatex-example] List of things to add to example

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luaharfbuzz#28]
This is an issue to track enhancements to the LuaTeX example code that uses Harfbuzz to shape text.

### Paragraph Handling
* [x] Fix widths of spacing glue in font loader
* [x] Refactor upem to sp scaling code
* [x] Add Devanagari example
* [x] Add Latin example
* [x] Set cluster level to HB_BUFFER_CLUSTER_LEVEL_CHARACTERS
* [x] Add sample PDFs
* [ ] Handle penalty nodes
* [ ] Handle different kinds of glue nodes
* [ ] Handle direction nodes
* [ ] Add ability to load packages using a PATH of some kind
* [ ] Handle font switching (includes switching the font style – like roman to italic or bold)
* [ ] Handle BiDi (look into libraqm and FriBidi code to get a better understanding)
* [ ] Alignment
* [ ] Handle hyphenation and corresponding change to shaping.

### Font Loading Callback
* [ ] Add support for handling features

### Testing and Control
* [ ] Can we turn Harfbuzz shaping on/off (using an attribute or something)
* [ ] Can we test code with busted or something?

### HBox Handling
_TODO_

**Comment by deepakjois** [comment]
Closed in favor of deepakjois/luatex-harfbuzz#1

**Comment by deepakjois** [comment]
There are some  things that I have come to realize since the time I first looked into integrating Harfbuzz with LuaTeX.

For non-Latin, complex scripts like Indic scripts, Arabic etc., it is already too late to do anything once the Node list is constructed by (Lua)TeX. So the callbacks are pretty useless. What we need is to access the text long before that. LuaTeX does have callbacks to process the input buffer (`process_input_buffer`), but it is awkward and insufficient IMO.

One possible solution is to ditch the macro language features of LuaTeX altogether, and programmatically access the node building routines using its Lua API. This allows us to do all the text processing, i.e. BiDi reordering, script itemization, shaping (maybe even hyphenation), using Lua code, then build the node list programmatically and finally tell LuaTeX to write the output to PDF. The flipside is that we are giving up on the ecosystem of TeX formats and macros that has been built up over the years. But I believe the tradeoff is worth it. I have literally spent _hours_ trying to read and understand TeX sources, and I have little progress to show for it. It’s just too confusing and archaic. I would we willing to give up a lot to just use a modern programming language like Lua all throughout.

I have started going down this path with a new package called [ufy](https://github.com/deepakjois/ufy) (name derived by taking the subsequent letters of ‘t’, ‘e’ and ‘x’) respectively. But it will take a while before everything is in place to do serious typesetting with it.

**Comment by michal-h21** [comment]
I don't think that it is too late to do the advanced stuff in the node callbacks - you can process the node list, make chunks of strings with the same language, font, direction, etc., hyphenate these strings, shape them, add kerning, fix directions, discard old nodes and create the new ones from the shaped text. 

I've tried that in my [shaper](https://github.com/michal-h21/luatex-harfbuzz-shaper/blob/master/hb_shaper.lua). Direction handling and hyphenation seems to be unfortunately broken at the moment, because of non-backward compatible changes in LuaTeX 0.9 and 1.0. It has also other problems, most notably due to the fact that words are shaped, instead of the whole chunks, so font features which include spaces can't work. I should really fix it eventually :)

Another issue which needs to be cared of is linebreaking, which can be controlled in the `linebreak_filter` callback. Node list can be broken using `tex.linebreak` function, but it probably can't work correctly in non-latin scripts, so custom line breaker which uses different methods for particular scripts is needed.

Do you have some concrete example what can't be handled on the node level? 

If I wanted to ditch the TeX macro system, I would use XML or HTML 5 with CSS as input - this way any sensible source format (Markdown, Word, even LaTeX) could be converted to sensible base format, with visual appearance defined in CSS, and it should be quite easy to typeset it. The hard thing is of course HTML and especially CSS parsing, of course :)

**Comment by deepakjois** [comment]
On Thu, Oct 20, 2016 at 7:07 PM, Michal Hoftich <notifications@github.com>
wrote:

> Do you have some concrete example what can't be handled on the node level?
>
Well, one obvious problem is that generally speaking, we can’t get back the
original input from the user once the node list has been constructed. The
glue that was inserted could have been a space, or a glue that was manually
inserted. There is no way of knowing that.

To solve this problem cleanly, we need access to the tokens that generated
the nodes. A callback like pre_linebreak_filter is too late.


> If I wanted to ditch the TeX macro system, I would use XML or HTML 5 with
> CSS as input - this way any sensible source format (Markdown, Word, even
> LaTeX) could be converted to sensible base format, with visual appearance
> defined in CSS, and it should be quite easy to typeset it. The hard thing
> is of course HTML and especially CSS parsing, of course :)
>
> I would like to ditch the TeX macro system, but the core typesetting
engine is still pretty effective, and it would be a LOT of effort to
replicate that. HTML/CSS may work well for digital environments, but not
for generating PDFs and printed documents. So I would like to retain the
TeX engine for now.

Markdown is definitely an option I am considering for inputting text. The
cmark Lua library converts a markdown document into well-defined node
objects which can be traversed in Lua and converted to equivalent TeX
nodelists (after doing other things like Bidi reordering, shaping and
hyphenation). The documents should be written in a human-friendly markup
system. Lua will only be used for orchestration.

Having said that, I am not against the idea of using Harfbuzz with LuaTeX
macro environments. My frustration with the macro language discourages me
to invest any effort into it though. However, all the modules I have
developed so far (luaharfbuzz, luaucdn and luabidi) were all made with the
intention that anybody could use it, either inside LuaTeX environments or
outside it.
